language: node_js

node_js:
  - "10"
  - "9"
  - "8"

install:
  - npm i
  - npm install --no-save istanbul@next coveralls

script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -rf ./coverage

notifications:
  email:
    on_success: never
    on_failure: always
